### ISSUE TITLE
Error when loading pre-trained models

### ISSUE THREAD

**Issue by TDeVries** [plemeri/InSPyReNet#1]
Great work! The results look very nice. I was hoping to try out the pretrained models but I am getting errors when trying to load the checkpoints.

`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

I was wondering if this error is only on my end, or if there is an issue with the checkpoint files somehow?

**Comment by plemeri** [comment]
Hello, Thank you for your interest. I wonder why the `zip` error came out because our checkpoint file extension is `.pth`.
Can you check if the checkpoint file name is `latest.pth` and the file is located as `snapshots/InSPyReNet_SwinB/latest.pth`?

**Comment by TDeVries** [comment]
Yes, the filepath and filename are correct.

Ah, I think the problem may be that it didn't download the entire file for some reason. My checkpoint files are only about 100MB, but it looks like they should be closer to 350MB.

**Comment by plemeri** [comment]
Please let me know if you need other download link.

**Comment by TDeVries** [comment]
If you have any other link that would be very helpful! The existing ones keep timing out before I can get the full file for some reason.

**Comment by plemeri** [comment]
I just updated [ReadMe](https://github.com/plemeri/InSPyReNet/blob/main/README.md) by adding google drive (GDrive) links for all assets that we provide. Hope this works!

**Comment by TDeVries** [comment]
I can download the full files now, thank you! 
It looks like there might be some permissions block on the new massive SOD dataset one though.

**Comment by TDeVries** [comment]
Got around to testing this. Amazing results! Thanks again for your responsive help!
