### ISSUE TITLE
Compressed Model

### ISSUE THREAD

**Issue by rakesh-reddy95** [plemeri/InSPyReNet#12]
Have you tried compressing the model for mobile devices. As the model size is large. Or if you can give suggestions in terms of deploying the solution on mobile.

**Comment by plemeri** [comment]
Our approach is targeting High-Resolution images without resizing, so it would be hard to deploy on mobile devices.
Actually there are many utilities to optimize model into smaller sizes, but I cannot sure about the efficacy.
