### ISSUE TITLE
Training Swin Transformer?

### ISSUE THREAD

**Issue by rakesh-reddy95** [plemeri/InSPyReNet#13]
I see that there are changes in comparison with the official implementation of Swin Transformer. Also is the Swin transformer getting trained while training Inspyrenet?

**Comment by plemeri** [comment]
Hi, we follow the official implementation of Swin Transformer from their [Semantic Segmentation version](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation). Although we did not mention in the paper, there are some minor changes to provide intermediate feature maps.

We train both backbone while training our model, so if you use our method with swin transformer (InSPyReNet_SwinB), then every parameter in the network is participating to the training.

Thank you and feel free to ask more question 😄

**Comment by rakesh-reddy95** [comment]
Thank you.
