### ISSUE TITLE
Edges are not high quality when trained with Swin Tiny version

### ISSUE THREAD

**Issue by rakesh-reddy95** [plemeri/InSPyReNet#18]
While training with SwinB (384* 384) and keeping the dynamic resize to 1280 during inference I see a high quality edges without any lack of global object saliency. But when train a Tiny version of SwinTransformer (224* 224) I see the global object saliency is lacking and not getting the high quality edges. May I know if I have to change anything for tiny versions  or any suggestions here?

**Comment by plemeri** [comment]
Hi, try reducing dynamic resize into somewhere between 768 ~ 1024.
