### ISSUE TITLE
Any suggestions on how to improve results for individual strands of hair?

### ISSUE THREAD

**Issue by RahulSinghalChicago** [plemeri/InSPyReNet#20]
I'm trying to use on some HR photography where the hair super important.

Any suggestions on model adjustments, additional training or would subsampling work?

**Comment by plemeri** [comment]
Hello, I would recommend using our model trained with composite datasets [Plus_Ultra](Ihttps://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md#-trained-with-massive-sod-datasets-with-lr-384-x-384-and-hr-1024-x-1024-not-in-the-paper-for-real-world-scenarios).

Also, we released python API / CLI tool using above checkpoint [`transparent_background`](https://github.com/plemeri/transparent-background).

However, if the result is still not good enough for your work, I would recommend visiting [MODNet](https://github.com/ZHKKKe/MODNet) which targets only human.

Thank you
