### ISSUE TITLE
The checkpoints of [web-demo] usage

### ISSUE THREAD

**Issue by myhz0606** [plemeri/InSPyReNet#21]
Can you tell me the [web-demo](https://huggingface.co/spaces/taskswithcode/salient-object-detection)'s checkpoint? I try to infer with these checkpoints

- InSPyReNet_SwinB_DIS5K
- InSPyReNet_SwinB_DIS5K_LR
- [Plus_Ultra_LR](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra_LR.yaml)
- [Plus_Ultra](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra.yaml)

But I can't attach the same result of [web-demo](https://huggingface.co/spaces/taskswithcode/salient-object-detection)
Looking forward to your response!

**Comment by plemeri** [comment]
Hi, the purpose of the web demo shows the main results of our paper.
The checkpoint which is used in the web demo is trained with DUTS-TR only with LR scale ($384 \times 384$).
You can find it in this [Link - InSPyReNet_SwinB](https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md#trained-with-lr-dataset-only-duts-tr-384-x-384).

Thank you.

**Comment by myhz0606** [comment]
Thank you for your reply. I get the same result of the web demo show. 
Thanks a million.
