### ISSUE TITLE
Wrong links on Model Zoo page

### ISSUE THREAD

**Issue by vani-or** [plemeri/InSPyReNet#24]
Hello, I've noticed that there's a problem with the links on the Model ZOO page to the "Trained with massive SOD datasets". I speak only about HR SwinB line, not the LR. So

1. Gdrive and OneDrive links are swapped
2. The links bring to two different files with different hashes and different performance. The one from OneDrive (the column Gdrive) brings to poor results respect to the other one.

**Comment by plemeri** [comment]
Thank you for letting me know the issue. I'll fix the links.

**Comment by plemeri** [comment]
We fixed the issue. Thank you again for letting me know the issue.
