### ISSUE TITLE
Not getting the same quality as the hugging face web demo model

### ISSUE THREAD

**Issue by yaju1234** [plemeri/InSPyReNet#30]
Hi @plemeri 

This is to inform you that when I test the hugging face model and compare the quality against this model which is trained with LR dataset only (DUTS-TR, 384 X 384)  InSPyReNet_SwinB https://github.com/plemeri/InSPyReNet/blob/main/configs/InSPyReNet_SwinB.yaml) then i am getting 2 different outputs and the quality differs and we see an outline forming and when we inference with the same image and the outline doesn't exist in the web demo model. 

Can you please tell me why this is occurring as i see from one of the old thread that you say that the model that is being used in the web demo is  InSPyReNet_SwinB trained with LR dataset only DUTS-TR, 384 X 384 so i dont understand why should there be any difference in the qualities. 

Please see the attached original image , output from the hugging face model and output from inference Trained with LR dataset only (DUTS-TR, 384 X 384). InSPyReNet_SwinB 

Also can you please let me know the versions that you are using for torch , torch vision and opencv-python and do u think that this can occur because there might be due to a change in the versions ? 

Original image : 

![6666666](https://github.com/plemeri/InSPyReNet/assets/1842237/abc10e99-a7ea-4da7-96a1-6e595d6ac9b3)

Output from Huggingface Model : 

![ss_test_rgba_6666666](https://github.com/plemeri/InSPyReNet/assets/1842237/2b82796a-c910-44ba-85e4-82424b28909e)

Output from inference with InSPyReNet_SwinB which is trained with LR dataset only (DUTS-TR, 384 X 384) :

![6666666](https://github.com/plemeri/InSPyReNet/assets/1842237/3534316f-5573-43c0-8c95-e9be061b28df)

P.S. download and zoom the image boundaries to see the differences between both the outputs. 

Also can you please tell me if you are doing any post processing in the hugging face demo. 

Looking forward to your reply.

**Comment by taha-azzabi** [comment]
maybe you could check the source code on Hugging face https://huggingface.co/spaces/taskswithcode/salient-object-detection/blob/main/app.py

**Comment by plemeri** [comment]
Hi @yaju1234, 
As @taha-azzabi mentioned above, huggingface demo is not maintained by us. The demo version is a [forked version](https://github.com/taskswithcode/InSPyReNet) which is maintained by @taskswithcode.

Also, as I know, the demo version used CPU backend which may cause the difference.
Thank you.
