### ISSUE TITLE
Unexpected keys in state_dict when trying inference

### ISSUE THREAD

**Issue by jwb95** [plemeri/InSPyReNet#32]
Hello,

I would simply like to inference the model.
Downloaded the checkpoint `swin_base_patch_4_window12_384_22kto1k.pth` and placed it in the snapshots folder, renamed it to `latest.pth`.

Running 
`python run/Inference.py --config configs/InSPyReNet_SwinB.yaml --source [SOURCE] --dest [DEST] --type [TYPE] --gpu --jit --verbose`
gives a torch key-error when trying to load from the checkpoint. It seems that the expected architecture differs from the one in the .ckpt-file.

Thank you

**Comment by plemeri** [comment]
Hi @jwb95,

The checkpoint that you've downloaded is for training the model with ImageNet initialized backbone model which has less parameters for the whole network architecture of InSPyReNet.

The checkpoint you're looking for are available on [Model Zoo](https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md).

Thank you
