### ISSUE TITLE
Model difference between Res2Net50 Backbone and Res2Net50 [DUTS-TR] trained checkpoint

### ISSUE THREAD

**Issue by HappyBang-ai** [plemeri/InSPyReNet#33]
Thank you for your amazing paper, I was really facinated by your works.

But when I run inference code about Res2net50, It stucked by error which is about state_dict error
SwinB works well but only for Res2net50. 
I attached my run command and error.

**run command**
 python run/Inference.py --config configs/InSPyReNet_Res2Net50.yaml --source myfolder --type rgba --gpu --verbose

**error**
RuntimeError: Error(s) in loading state_dict for InSPyReNet:
	Unexpected key(s) in state_dict: "backbone.fc.weight", "backbone.fc.bias". 

I download checkpoint by here 
(https://github.com/plemeri/InSPyReNet/blob/main/docs/getting_started.md )
and checkpoint by here 
(https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md)

Thanks.

**Comment by HappyBang-ai** [comment]
@plemeri Still doesn't work, 

RuntimeError: Error(s) in loading state_dict for InSPyReNet:
	Unexpected key(s) in state_dict: "backbone.fc.weight", "backbone.fc.bias". 

It makes same error message.

This is my InSPyReNet_Res2Net50.yaml file

Model:
    name: "InSPyReNet_Res2Net50"
    depth: 64
    pretrained: False
    base_size: [384, 384]
    threshold: NULL

Thanks.

**Comment by plemeri** [comment]
I'm so sorry about the problem. This checkpoint was trained when we did not removed the above `fc` layer in the `res2net` backbone. I'll fix this problem immediately.
