### ISSUE TITLE
`base_size` and `stage` parameters are not used for encoder and decoder

### ISSUE THREAD

**Issue by kuynzereb** [plemeri/InSPyReNet#35]
Hi, thank you for a great work!

I was digging into the used NN architecture and found out that `base_size` and `stage` parameters are not actually used inside `PAA_e` and `PAA_d` modules. They are used to initialize `stage_size` parameter which is then used in `SelfAttention` module. And the thing is that `SelfAttention` does not actually use this parameter.

I am just wondering, is it some sort of a bug and maybe the whole model may be further improved or these parameters simply should be not used in these modules?

**Comment by kuynzereb** [comment]
`SelfAttention` itself also looks suspicious. If input tensor is a square (i.e., `H` equals `W`), then `mode='h'` and `mode='w'` will lead to the very same output. These two modes are used in `PAA_kernel` and `PAA_d` modules, so I guess they are expected to produce different outputs.

**Comment by Amadeus-AI** [comment]
In InSPyReNet.py
```
self.context1 = PAA_e(self.in_channels[0], self.depth, base_size=self.base_size, stage=0)
self.context2 = PAA_e(self.in_channels[1], self.depth, base_size=self.base_size, stage=1)
self.context3 = PAA_e(self.in_channels[2], self.depth, base_size=self.base_size, stage=2)
self.context4 = PAA_e(self.in_channels[3], self.depth, base_size=self.base_size, stage=3)
self.context5 = PAA_e(self.in_channels[4], self.depth, base_size=self.base_size, stage=4)
```
As you can see the base_size and stage parameters are assigned here, so they are used.

**Comment by Amadeus-AI** [comment]
Interesting, if you have time I suggest you can dig into https://github.com/plemeri/UACANet, which is where PAA_e and PAA_d from.

**Comment by plemeri** [comment]
Hi, thanks for paying attention to our work.
We initially tried to solve a image resolution problem for Object Contextual Representation architecture which we have been used for the attention-based segmentation decoder and thought it might be useful for the other attention operations such as `PAA` modules but empirically we found that it wasn't necessary. Those parameters are deprecated and no longer in use.

**Comment by plemeri** [comment]
You are once again right about the problem. This was actually came from our previous work [UACANet - issue #8](https://github.com/plemeri/UACANet/issues/8) but we do not found any meaningful performance difference at that time, so we didn't change at that moment. 

If you're trying to do a research or developing your own work, you can either change it into the right source code or just leave it as is.

**Comment by kuynzereb** [comment]
Ok, thanks!
