### ISSUE TITLE
Some confusion about dynamic_resize

### ISSUE THREAD

**Issue by babyta** [plemeri/InSPyReNet#38]
When to use dynamic_resize and when to use static_resize during inference.
Can I understand that dynamic_resize is for compatibility with LR and HR images during inference? But in this case, the large image may burst the gpu memory.

**Comment by plemeri** [comment]
Hi @babyta, `dynamic_resize` is used to downsample HR images larger than about 1K pixels. It is fair to use `static_resize` as you want for LR or HR images. You can set `static_resize.size=[1024, 1024]` for HR images, while `[384, 384]` for LR images.

**Comment by babyta** [comment]
I understand, thank you！
