### ISSUE TITLE
InSPyReNet for mask refinement?

### ISSUE THREAD

**Issue by noahcoolboy** [plemeri/InSPyReNet#42]
Hi there!

Thank you for your great work on this project.
I was wondering if InSPyReNet could take in a pre-computed mask instead of generating one on its own.
InSPyReNet excels at fine details, but sometimes does not include the objects I would like in the image.
I have a list of images along with their trimaps, and would like for InSPyReNet to refine the edges for a smooth background removal.

Is this possible, and if so, what would be a good way to take on this challenge?

Thank you!

**Comment by plemeri** [comment]
Hi @noahcoolboy, we actually tried this and turned out it didn't work that we expected. However, there are some good studies on mask refinement task such as CascadePSP. 

They don't generate the mask itself in a standalone manner, but they are really good at refining the coarse mask.
