### ISSUE TITLE
InSPyReNet_SwinB_DIS5K_LR	Result Download Failed

### ISSUE THREAD

**Issue by m0ho** [plemeri/InSPyReNet#45]
Thank you for your excellent works. But  I came into an error when downloading DIS-TE2 results of InSPyReNet_SwinB_DIS5K_LR.
Can you please re-upload this results.

![image](https://github.com/plemeri/InSPyReNet/assets/53399353/83ba88d8-ceb7-4f3b-8438-70d2ddafb372)
![image](https://github.com/plemeri/InSPyReNet/assets/53399353/053a5c9b-1cfa-4f98-bd5e-d63ca13d6120)

**Comment by plemeri** [comment]
Hi, I just fixed the broken url. Please check the latest document. 

Thanks
