### ISSUE TITLE
The setting of threshold in Plus_Ultra.yaml

### ISSUE THREAD

**Issue by mingheyuemankong** [plemeri/InSPyReNet#52]
Outstanding work.

But I have the following question, in the Plus_Ultra.yaml file, the threshold of the model is set to NULL by default, which means that in the current configuration, Pyramid Blending as mentioned in the paper is not used in the inference phase, why?

![image](https://github.com/user-attachments/assets/a9e6a468-9bfb-477e-9c3d-287a5f1d4e54)
![image](https://github.com/user-attachments/assets/d0f93367-df6e-40db-89fb-020333f2c00c)

**Comment by plemeri** [comment]
Hi @mingheyuemankong. Please refer to https://github.com/plemeri/transparent-background/issues/24.

**Comment by mingheyuemankong** [comment]
I see, thanks for your response, good luck!
