### ISSUE TITLE
Safetensor Models for Human Subjects

### ISSUE THREAD

**Issue by reefor** [plemeri/InSPyReNet#55]
Hi. I love your node for background removal, but I'd also love to find a model to improve on it, especially making edges smoother.

I looked at the Model Zoo but didn't see any other models to try that are Safetensors and I've been warned about using anything except Safetensors. I'm also not knowledgeable enough to set up a Sandbox to test pth models.

Also, the models don't give info about which are trained for human subjects.

Does anyone know of a Safetensor model that would improve & smoothen edges on human subjects?

Or does anyone know of an easy to use program to convert pth to safetensor?

Thanks

**Comment by LukaGiorgadze** [comment]
Try this: https://github.com/Photoroom/fast-foreground-estimation
